services:
  static-site:
    image: nginx:alpine
    container_name: static-site
    restart: unless-stopped
    networks:
      - npm_network
    volumes:
      - ./html:/usr/share/nginx/html:ro

networks:
  npm_network:
    external: true
